# Welcome to MyBlog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: UTF-8
title: 等一等
email: dengdeng1ba@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Record my daily life
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deng1deng.com" # the base hostname & protocol for your site
twitter_username: None
github_username:  none

# Build settings
markdown: kramdown
#设置固定链接
permalink: /:categories/:year/:month/:day/:title